# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linearIsh,0.5,0.5,0.75,1.0
    animation = fadeIn, 1, 1, linearIsh
    animation = fadeOut, 1, 1, linearIsh
    animation = inputFieldDots, 1, 1, linearIsh
    animation = inputFieldColors, 1, 1, linearIsh
    animation = inputFieldFade, 1, 1, linearIsh
    animation = inputFieldWidth, 1, 1, linearIsh
}

background {
    monitor =
    path = ~/wallpapers/forest_fog_trees.jpg
    blur_passes = 3
}

input-field {
    monitor =
    size = 400px, 45px 
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgb(3b4252)
    check_color = rgb(bdbdbd)
    fail_color = rgb(ff7161)

    font_color = rgb(bdbdbd)
    fade_on_empty = false
    rounding = 12

    font_family = $font
    placeholder_text = Password
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    dots_size = 0.1
    dots_spacing = 0.4

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}
