[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #1F1F1F26
foreground = #FFFFFF
foreground-alt = #FFFFFF

;; shades
shade1 = #101e36
shade2 = #16305e
shade3 = #234c91
shade4 = #3669bf
shade5 = #2196F3
shade6 = #42A5F5
shade7 = #64B5F6
shade8 = #90CAF9

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
